config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cart, only: [:new]
  resources :candies, only: [:index, :show]
  resources :customers, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord
     has_many :cart_candies
     has_many :carts, through: :cart_candies
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :customer
    has_many :cart_candies
    has_many :candies, through: :cart_candies
end

app/models/cart_candy.rb
class CartCandy < ApplicationRecord
    belongs_to :candy 
    belongs_to :cart
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  def index
    @candies = Candy.all
  end

  def show
    @candy = Candy.find(params[:id])
  end

  
end

app/controllers/cart_candies_controller.rb
class CartCandiesController < ApplicationController
    def index

    end

    def show

    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all 
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candys_helper.rb
module CandysHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/candies/index.erb
<h1>Candies</h1>
    <% @candies.each do |c| %>
        <li><%= link_to c.name, candy_path(c) %></li>
    <% end %>

app/views/candies/show.erb
<h1><%= @candy.name %> Details</h1>
<div>
<li> Type: <%= @candy.candy_type %> </li>
<li> Flavor: <%= @candy.flavor %> </li>
<p> Description: <%= @candy.description %> </p>

<%= link_to "Return to Candy Galore", candies_path %>

app/views/customers/index.erb
<h1>Customers</h1>
<% @customers.each do |c| %>
    <li><%= link_to c.f_name + " " + c.l_name, customer_path(c) %></li>  
<% end %>

app/views/customers/show.erb
<h1><%= @customer.f_name %>'s Details </h1>

<p>Name: <%= @customer.f_name %> <%= @customer.l_name %></p>
<p>Username: <%= @customer.username %></p>

<%= link_to "Back to Candies Galore", candies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class "header">
          <h4>Welcome <%=  %></h4>
    </div>
    <%= yield %>
  </body>
</html>